[package]
name = "parser-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
derive_more = { version ="1", features = ["full"] }
genco = "0.17.9"
itertools = "0.13.0"
